name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  CI:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }} 
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }} 
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }} 
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Generate prisma client
        run: npx prisma generate

      - name: Run linting
        run: pnpm lint:fix

      - name: Build Next.js app
        run: pnpm build
