name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"



jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm lint

      - name: Build Next.js app
        run: pnpm build
